# Generated by Django 6.0.5 on 2026-05-24 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(max_length=200)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='autorzy/')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gatunek',
                'verbose_name_plural': 'Gatunki',
            },
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=300)),
                ('opis', models.TextField(blank=True)),
                ('data_wydania', models.DateField(blank=True, null=True)),
                ('okladka', models.ImageField(blank=True, null=True, upload_to='okladki/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksiazki', to='books.autor')),
                ('gatunek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ksiazki', to='books.gatunek')),
            ],
            options={
                'verbose_name': 'Książka',
                'verbose_name_plural': 'Książki',
            },
        ),
        migrations.CreateModel(
            name='Egzemplarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('dostepny', 'Dostępny'), ('wypozyczony', 'Wypożyczony'), ('zarezerwowany', 'Zarezerwowany')], default='dostepny', max_length=20)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egzemplarze', to='books.ksiazka')),
            ],
            options={
                'verbose_name': 'Egzemplarz',
                'verbose_name_plural': 'Egzemplarze',
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rezerwacji', models.DateTimeField(auto_now_add=True)),
                ('data_waznosci', models.DateTimeField()),
                ('egzemplarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='books.egzemplarz')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
    ]
