# Generated by Django 6.0.5 on 2026-05-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='jezyk',
            field=models.CharField(choices=[('pl', 'Polski'), ('en', 'Angielski'), ('de', 'Niemiecki'), ('fr', 'Francuski'), ('es', 'Hiszpański'), ('it', 'Włoski'), ('ru', 'Rosyjski'), ('inne', 'Inny')], default='pl', max_length=10),
        ),
    ]
