# Generated by Django 6.0.5 on 2026-06-01 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_ksiazka_jezyk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RezerwacjaOczekujaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zgloszenia', models.DateTimeField(auto_now_add=True)),
                ('aktywna', models.BooleanField(default=True)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oczekujace_rezerwacje', to='books.ksiazka')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oczekujace_rezerwacje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zgłoszenie rezerwacji',
                'verbose_name_plural': 'Zgłoszenia rezerwacji',
            },
        ),
    ]
