# Generated by Django 6.0.5 on 2026-06-01 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rezerwacjaoczekujaca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacjaoczekujaca',
            name='powiadomiony',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=220)),
                ('tresc', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('utworzone', models.DateTimeField(auto_now_add=True)),
                ('przeczytane', models.BooleanField(default=False)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powiadomienia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
            },
        ),
    ]
