# Generated by Django 6.0.5 on 2026-06-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rezerwacjaoczekujaca_powiadomiony_powiadomienie'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='data_zwrotu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
